services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_script:
  - openssl enc -in godinary-e7f1383f7309.json.enc -d -aes-256-cbc -pass env:GODKEY > godinary-e7f1383f7309.json

script:
  - make build-test
