apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    project: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Chart.Name }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.hpa.resourceName }}
      targetAverageValue: {{ .Values.hpa.resourceAverage }}
