apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Chart.Name }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value }}
    {{- end}}
  {{- end }}
  labels:
    project: {{ .Chart.Name }}
spec:
  ports:
  - name: {{ .Chart.Name }}-http
    port: {{ .Values.service.frontalPort }}
    targetPort: {{ .Chart.Name }}-port
    protocol: {{ .Values.service.protocol }}
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  selector:
    project: {{ .Chart.Name }}
